### ISSUE TITLE
fail to build instance for Data.Functor.Classes.Show1

### ISSUE THREAD

**Issue by amigalemming** [anton-k/hindley-milner-type-check#5]
I am trying to build the package with recent GHC, but I get:
~~~~
Build profile: -w ghc-9.8.4 -O1
In order, the following will be built (use -v for more details):
 - data-fix-0.3.4 (lib) (requires build)
 - data-ref-0.1 (lib) (requires build)
 - dlist-1.0 (lib) (requires build)
 - prettyprinter-1.7.1 (lib) (requires build)
 - th-abstraction-0.7.1.0 (lib) (requires build)
 - transformers-compat-0.7.2 (lib) (requires build)
 - deriving-compat-0.6.7 (lib) (requires build)
 - hindley-milner-type-check-0.1.1.0 (lib) (requires build)

...

[3 of 9] Compiling Type.Check.HM.Term ( src/Type/Check/HM/Term.hs, dist/build/Type/Check/HM/Term.o, dist/build/Type/Check/HM/Term.dyn_o )

src/Type/Check/HM/Term.hs:75:2: error: [GHC-39999]
    • Could not deduce ‘Data.Functor.Classes.Show1 (Bind loc v)’
        arising from a use of ‘Data.Functor.Classes.liftShowList’
      from the context: (Show prim, Show loc, Show v)
        bound by the instance declaration
        at src/Type/Check/HM/Term.hs:75:2-22
    • In the second argument of ‘Data.Functor.Classes.liftShowsPrec’, namely
        ‘(Data.Functor.Classes.liftShowList sp1_avJn sl1_avJo)’
      In the first argument of ‘(.)’, namely
        ‘Data.Functor.Classes.liftShowsPrec
           (Data.Functor.Classes.liftShowsPrec sp1_avJn sl1_avJo)
           (Data.Functor.Classes.liftShowList sp1_avJn sl1_avJo) 11 arg2_avJM’
      In the second argument of ‘(.)’, namely
        ‘(Data.Functor.Classes.liftShowsPrec
            (Data.Functor.Classes.liftShowsPrec sp1_avJn sl1_avJo)
            (Data.Functor.Classes.liftShowList sp1_avJn sl1_avJo) 11 arg2_avJM
            . (GHC.Show.showSpace . sp1_avJn 11 arg3_avJN))’
   |
75 | $(deriveShow1 ''TermF)
   |  ^^^^^^^^^^^^^^^^^^^^^
~~~~

I guess this is due to some incompatible changes in `transformers`?

**Comment by amigalemming** [comment]
I can compile with GHC-8.10.7, but with GHC-9.0.2 and later it fails. So seems to be related to a change in TemplateHaskell.

**Comment by amigalemming** [comment]
It seems some problems with Template Haskell were eliminated a year ago. They are contained in the repository, but not released at Hackage. With those changes I can compile with GHC up to 9.4.8. But with GHC-9.6.6 I get:
~~~~
src/Type/Check/HM/Term.hs:84:2: error: [GHC-39999]
    • Could not deduce ‘Ord (Bind loc var a)’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
      from the context: (Ord loc, Ord var)
        bound by the instance declaration
        at src/Type/Check/HM/Term.hs:84:2-21
      or from: Ord a
        bound by a quantified context at src/Type/Check/HM/Term.hs:84:2-21
    • In the instance declaration for
        ‘Data.Functor.Classes.Ord1 (Bind loc var)’
   |
84 | $(deriveOrd1  ''Bind)
   |  ^^^^^^^^^^^^^^^^^^^^
~~~~

**Comment by amigalemming** [comment]
I think the types `Term.TermF`, `Term.CaseAlt`, `Term.Bind` and `TyTerm.Ann` are simply missing the deriving `Ord` clauses.
